rungalileo/dataquality

dataquality/dq_auto/auto.py
=> auto docs update

dataquality/__init__.py, dataquality/schemas/metrics.py
we changed the default LM percentile to 100% (which is a dep percentile of 0), but never updated the dq client.
=> UI changed LM default to 100%

dataquality/integrations/torch.py, dataquality/utils/torch.py
- Try catch reference errors
- Unpatch on start to false per default
- Added better description to classifier_layer
=> Setting unpatch on start to false per default

dataquality/core/log.py, dataquality/loggers/data_logger/structured_classification.py, tests/loggers/test_structured_classification.py
I'm sure we will fully replace `: xgb.XGBClassifier` with sklearn estimator some time very soon, but just not yet. bigger fish to fry in short term
=> XGB type checking only

dataquality/core/finish.py, dataquality/loggers/data_logger/structured_classification.py, dataquality/loggers/logger_config/base_logger_config.py, docs/Structured-Data.ipynb, tests/loggers/test_structured_classification.py
Adding a `features.hdf5` DF and predictions to the data df
Produced on local 👇
=> Add features df and pred to data

dataquality/utils/imports.py
Forgot to remove the imports after removing the lazy import function
=> Remove unused imports

dataquality/__init__.py, dataquality/dq_auto/auto.py, dataquality/dq_auto/notebook.py, dataquality/utils/auto.py, dataquality/utils/version.py, tests/utils/test_version.py
auto notebook for jupyter support. Upload button and click go
top level, `dq.auto_notebook()`
notebook to play with https://urshr-demo.notebook.us-west-1.sagemaker.aws/notebooks/Auto%20notebook%20Demo.ipynb
and nothing breaks if ipywidgets isn't installed. Graceful error if you try to use this but you don't have the necessary notebook packages
=> auto notebook with upload button

dataquality/__init__.py, dataquality/clients/api.py, dataquality/clients/objectstore.py, dataquality/loggers/data_logger/image_classification.py, dataquality/loggers/data_logger/structured_classification.py, dataquality/utils/cv.py, dataquality/utils/dq_logger.py, dataquality/utils/hf_images.py, tests/loggers/test_image_classification.py, tests/loggers/test_structured_classification.py
No issue. This uploads images to minio and retrieves them via presigned url.
Locally!
=> cv: image opti

dataquality/loggers/model_logger/base_model_logger.py, dataquality/loggers/model_logger/text_classification.py, dataquality/loggers/model_logger/text_ner.py
apparently they are really slow 😭 
Thanks @rfriel !
=> remove debug logging

dataquality/core/finish.py, dataquality/dq_auto/auto.py, dataquality/dq_auto/text_classification.py, dataquality/utils/auto_trainer.py, dataquality/utils/helpers.py
https://app.shortcut.com/galileo/story/3827/create-data-embs-defaults-to-true-if-a-gpu-is-available
=> gpu available for create data embs

dataquality/dq_auto/ner_trainer.py, dataquality/dq_auto/tc_trainer.py, dataquality/utils/helpers.py
For example, what are the exact commands you ran and their output, related screenshots, screen-recordings, test runs, anything that can showcase.
***Provide additional context.***
Provide as much relevant context as you like.
=> [Feature] Use MPS support when available for dq.auto

dataquality/integrations/hf.py
=> support hf datat with no gold spans

dataquality/loggers/data_logger/image_classification.py, dataquality/utils/keras.py
fix for ic prob only when embs missing
=> fix for ic prob only when embs missing

dataquality/loggers/data_logger/base_data_logger.py, dataquality/loggers/model_logger/base_model_logger.py, tests/test_dataquality.py
=> fix: client side f32 validation

dataquality/__init__.py, dataquality/integrations/hf.py
=> filter and warn on empty tokens

.gitignore, dataquality/integrations/torch.py, dataquality/loggers/base_logger.py, dataquality/loggers/data_logger/base_data_logger.py, dataquality/loggers/data_logger/structured_classification.py, dataquality/loggers/data_logger/text_classification.py, dataquality/loggers/data_logger/text_multi_label.py, dataquality/loggers/data_logger/text_ner.py, dataquality/loggers/model_logger/base_model_logger.py, dataquality/loggers/model_logger/text_classification.py, dataquality/loggers/model_logger/text_multi_label.py, dataquality/loggers/model_logger/text_ner.py, docs/autodocs/_build/markdown/api/dataquality.md, tests/inference/test_text_classification_inf.py, tests/inference/test_text_ner_inf.py, tests/loggers/test_structured_classification.py, tests/test_dataquality.py
Rename fn to validate and format, plus add CV files to gitignore
=> Rename to validate and format, plus gitignore

pyproject.toml
=> fix: test dep

dataquality/clients/api.py
Use post instead of get for metadata
=> Use post instead of get for metadata

dataquality/clients/api.py, dataquality/clients/objectstore.py, dataquality/core/_config.py, dataquality/core/init.py, pyproject.toml, tests/core/test_init.py, tests/integrations/fastai/test_cv_fai.py, tests/integrations/hf/test_hf_integration.py, tests/loggers/test_structured_classification.py, tests/start/test_start_auto.py, tests/start/test_start_hf.py, tests/start/test_start_keras.py, tests/start/test_start_pt.py, tests/utils/test_dq_logger.py
Story details: https://app.shortcut.com/galileo/story/4518
=> fix: [sc-4518] exoscale presigned url rework

dataquality/dq_auto/auto.py
=> return after demo run

scripts/test.sh
=> tests in dq are longngngngng

.github/workflows/test.yaml, dataquality/__init__.py, pyproject.toml, scripts/install.sh
=> chore: adjust deps, alpha build

dataquality/__init__.py, pyproject.toml
=> fix: transformers update

.github/CODEOWNERS, dataquality/__init__.py, dataquality/dq_auto/ner_trainer.py, dataquality/dq_auto/tc_trainer.py, pyproject.toml
=> chore: optional evaluate install

dataquality/dq_auto/auto.py
=> dq auto doc missing param

dataquality/core/log.py, dataquality/loggers/data_logger/base_data_logger.py, dataquality/loggers/data_logger/image_classification.py, dataquality/loggers/data_logger/object_detection.py, dataquality/loggers/data_logger/semantic_segmentation.py, dataquality/loggers/data_logger/text_classification.py, dataquality/loggers/data_logger/text_ner.py
=> Chore: Improve optional meta for linting

dataquality/__init__.py, dataquality/integrations/ultralytics.py, dataquality/loggers/data_logger/object_detection.py, tests/integrations/ultralytics/test_cv_yolo.py
width and height are necessary for OD dataframes
relates to https://app.shortcut.com/galileo/story/5206/edits-cart-fix-coordinates-format
=> add width and height to log

pyproject.toml
=> chore: update deps to include evaluate

dataquality/__init__.py, dataquality/core/log.py, dataquality/loggers/model_logger/semantic_segmentation.py, tests/core/test_log.py
https://galileoteamworkspace.slack.com/archives/C02NSBN4ZK3/p1683904619808329
https://github.com/rungalileo/dataquality/pull/590/files
=> Check sorted labels

dataquality/integrations/torch.py
=> Update torch.py watch docstr

dataquality/__init__.py, dataquality/integrations/fastai.py, tests/integrations/fastai/test_text_fai.py
- Quickest fix in history of DQ
Turns out the error was caused because the indices were a generator not a list.
Added test
=> Fix Iterable Index error

dataquality/loggers/data_logger/semantic_segmentation.py, dataquality/loggers/logger_config/semantic_segmentation.py, dataquality/loggers/model_logger/semantic_segmentation.py, dataquality/schemas/semantic_segmentation.py, dataquality/utils/semantic_segmentation/polygons.py
```
"No data found in minio for project / run (7e78e642-cc40-4f5c-8f45-b2cadd8d674a/c887c2e6-8699-4a90-b062-21cf0fdcaeea/training/contours/4.json)"
```
Running into a race condition issue getting / setting polygon idx
=> Set polygon idx in lock

dataquality/__init__.py, dataquality/integrations/setfit.py
This is a proposed fixed that might resolve quirks around the DEP reported for setfit
=> SetFit: When logging probs, log them not as logits

dataquality/__init__.py
Bumping the version to release
=> Bump version to release

dataquality/__init__.py, dataquality/analytics.py
=> Fixes traceback_offset None error

.github/workflows/test.yaml, tasks.py
=> closes #661

dataquality/integrations/torch_semantic_segmentation.py
Small wording changes for semseg notice about dataloaders
=> Wording changes

dataquality/__init__.py, dataquality/core/_config.py, dataquality/core/init.py, dataquality/dq_auto/auto.py, dataquality/dq_auto/ner.py, dataquality/dq_auto/text_classification.py, dataquality/integrations/setfit.py, dataquality/utils/auto_trainer.py, dataquality/utils/setfit.py, docs/autodocs/api/dataquality.rst, tasks.py, tests/integrations/setfit/test_setfit.py
- This adds validation to watch
- And it adds a dq auto function for end-to-end experience
=> SetFit Auto and Validation before training

dataquality/loggers/data_logger/text_classification.py
If we are running inference the label is None. This check if there is a label column supplied and then casts the column
=> Quick fix for inference

tests/integrations/torch/test_pt_text_classification.py
Create Mockdataset instead and remove AG_NEWS
=> Remove AG_NEWS dependency

dataquality/__init__.py, dataquality/dq_auto/base_data_manager.py, dataquality/integrations/setfit.py, dataquality/loggers/data_logger/text_classification.py, dataquality/utils/auto.py, dataquality/utils/setfit.py, tasks.py, tests/integrations/setfit/test_setfit.py
SetFit auto was only working for train and eval, now added training arguments and support for inference and test
=> Fix for SetFit Auto

dataquality/__init__.py
=> Bump patch version of dq

dataquality/schemas/semantic_segmentation.py
=> Dummy polygon defaults

dataquality/__init__.py
With spacy removal bump to 0.9.0
=> Bump version to 0.9.0

dataquality/__init__.py
https://github.com/rungalileo/dataquality/actions/runs/5358116969/jobs/9719939665
Since 0.9.0 was yanked we have to do 0.9.1
=> Bump version to 0.9.1 since 0.9.0 was yanked

dataquality/__init__.py
=> Bump version

dataquality/__init__.py, dataquality/loggers/base_logger.py, tests/test_dataquality.py
https://app.shortcut.com/galileo/story/6866/dq-remove-cloud-inference-restriction
=> Chore: Remove cloud inference restriction

dataquality/loggers/base_logger.py, dataquality/loggers/data_logger/seq2seq.py, dataquality/schemas/seq2seq.py, dataquality/utils/auto.py, docs/notebooks/Seq2Seq_Dq_Fake_Data.ipynb, tests/loggers/test_seq2seq.py
As per feedback on https://github.com/rungalileo/rungalileo/pull/792/files, we:
- rename `target_output` -> `target`
- no longer log `tokenized_label` in finalized df
Same thing happening here: https://github.com/rungalileo/runners/pull/423
=> fix: Remove unneeded column in s2s df

dataquality/schemas/task_type.py
***Provide additional context.***
Add llm_monitor task type to match the specs in rungalileo.
=> Add llm_monitor task type

dataquality/__init__.py
=> Bump version before release

.github/workflows/docs.yaml, docs/autodocs/api/dataquality.rst
This should fix the sync due to moved locations
=> Fix documentation sync

dataquality/__init__.py, dataquality/clients/api.py
Corollary to https://github.com/rungalileo/api/pull/1377.
=> fix(project): Set new projects to private by default

dataquality/integrations/jsl.py, dataquality/utils/jsl.py
=> Small bug fix regarding label matching in JSL

dataquality/__init__.py
release containing ultralytics fix
=> chore(release): 1.0.4

dataquality/__init__.py
=> chore(release): v1.1.0

dataquality/__init__.py, dataquality/dq_auto/schema.py, dataquality/integrations/seq2seq/auto.py, dataquality/integrations/seq2seq/s2s_trainer.py, dataquality/integrations/seq2seq/schema.py, dataquality/utils/torch.py
- increment `max_new_tokens` to 64
- Remove train print statements after eval loop
- Optionally return model (default to false, delete memory)
=> fix: s2s auto small improvements

dataquality/utils/torch.py
https://app.shortcut.com/galileo/story/8227/dq-move-model-to-cpu-before-cleanup
For @dcaustin33
=> fix: model to cpu for cuda cleanup

dataquality/__init__.py, dataquality/integrations/seq2seq/formatters/base.py
https://app.shortcut.com/galileo/story/8586/dq-sarah-s-issue-logging-1000-runs?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
We were passing in the dataset id not the batch id
=> fix: s2s chat batch idx

dataquality/__init__.py, dataquality/integrations/seq2seq/s2s_trainer.py
https://app.shortcut.com/galileo/story/8588/dq-seq2seq-auto-with-0-epochs-just-pass-over-data-no-backwards
Tested with run (0 epoch) https://console.dev.rungalileo.io/insights/e24eb571-8eaf-45a1-beb0-86c6488f4f1a/447524bc-6ab4-4e8d-9cb5-291046c7cd66?taskType=8
VS run for 1 epoch https://console.dev.rungalileo.io/insights/e24eb571-8eaf-45a1-beb0-86c6488f4f1a/b1a1c360-d9da-4cc9-b332-60723d41c964?taskType=8
=> Seq2Seq: Skip training if epoch=0

dataquality/__init__.py, dataquality/clients/api.py, dataquality/metrics.py
https://app.shortcut.com/galileo/story/8671/dq-get-dataframe-doesn-t-support-metadata
See also changes in API https://github.com/rungalileo/api/pull/1488
=> fix: include metadata cols in get dataframe

dataquality/__init__.py, dataquality/metrics.py
Follow up fix for https://github.com/rungalileo/dataquality/pull/787
=> fix: remove get df caching

dataquality/__init__.py
In this release we expose:
- Model embs support for seq2seq
- Directly logging log probs for seq2seq (instead of logits)
=> release: 1.3.1

dataquality/__init__.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py
Small issue Jon found in final e2e testing!
=> fix: model is not necessary if no generation

dataquality/__init__.py, dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/utils/seq2seq/decoder_only.py
Adds progress logging for two of the longer steps during `data_logging`. Specifically, tokenization and alignment is the bottleneck during data processing. So now we add the following progress bar logging steps:
1. `Identifying `response_template` to isolate response tokens`: When we loop through samples and locate the `response_template`
2. `Aligning string characters with tokenizer representation`: This is generally the biggest bottleneck, since we currently decode the `response_tokens` then re-tokenize them to get the offsets 😬. 
Overall these progress bars just make it feel a lot less daunting!
I also added a small change to the   `extract_tokenized_responses` that breaks early when we have found the response template in reverse …
=> Improved progress logging when processing data

docs/notebooks/Seq2Seq_Decoder_Only_Dq_Fake_Data.ipynb
Fix the decoder only notebook https://app.shortcut.com/galileo/story/9409/fix-decoder-only-notebook
=> fix: s2s decoder only notebook

dataquality/__init__.py, dataquality/analytics.py, dataquality/core/_config.py, dataquality/loggers/logger_config/base_logger_config.py, dataquality/loggers/logger_config/seq2seq/seq2seq_base.py, dataquality/loggers/logger_config/text_classification.py, dataquality/loggers/logger_config/text_multi_label.py, dataquality/loggers/logger_config/text_ner.py, dataquality/schemas/condition.py, dataquality/schemas/dataframe.py, dataquality/schemas/edit.py, dataquality/schemas/metrics.py, dataquality/schemas/report.py, dataquality/utils/semantic_segmentation/errors.py, pyproject.toml, tests/core/test_report.py, tests/inference/test_inference.py, tests/loggers/test_multi_label.py, tests/schemas/test_metrics.py
Shortcut: https://app.shortcut.com/galileo/story/8757/update-dataquality-to-pydantic-v2
The last Pydantic v1 package is also going to v2 🚀.
=> chore(deps): Update to `pydantic` v2

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, dataquality/dq_auto/base_data_manager.py, dataquality/integrations/setfit.py, dataquality/loggers/data_logger/__init__.py, dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/loggers/model_logger/__init__.py, dataquality/utils/seq2seq/logprobs.py, docs/cv/coco_hf_datasets.py, docs/source/conf.py, pyproject.toml, tasks.py, tests/integrations/keras/test_end2end_keras.py, tests/integrations/lightning/test_lightning.py, tests/loggers/test_seq2seq.py, tests/utils/test_seq2seq_utils.py
It really irked me that the `pre-commit` action was failing, so I just set the config correctly and applied it.
=> chore(pre-commit): Update ruff, isort, black config, apply to all files

dataquality/__init__.py, pyproject.toml
To get changes from https://github.com/rungalileo/dataquality/pull/847
=> fix(release): 2.1.1

dataquality/__init__.py, dataquality/loggers/data_logger/base_data_logger.py, pyproject.toml
**Shortcut:**
**Description:**
Fix a bug caused by processing random embeddings that we'd remove later anyways --> don't process if we remove them later.
**Tests:**
=> fix: s2s embedding bug

poetry.lock, pyproject.toml
Resolves:
- https://github.com/rungalileo/dataquality/security/dependabot/13
- https://github.com/rungalileo/dataquality/security/dependabot/8
=> chore(deps-test): Update `lightning` to latest to resolve remote execution CVEs

dataquality/__init__.py, pyproject.toml
Just releasing since I want to get #876 out.
=> chore(release): Bump version to v2.2.1
