dataquality/__init__.py
because for some reason the deprecation warning wouldn't show up in jupyter :/
=> deprecate configure function

dataquality/__init__.py, dataquality/loggers/data_logger/image_classification.py, dataquality/utils/cv.py, tests/loggers/test_image_classification.py
When an image dataset is logged to Galileo, we convert the image data into a base64 encoded string.  Currently, what we do is
1. Load an image path into a PIL `Image`
2. Get the MIME type from the `Image`
3. Get bytes from the image by calling `Image.save`, using the same image format 
4. Combine the bytes and the MIME type and UTF-8 encode them to a string
This is wasteful, because we already have bytes on disk -- that is what we load in step 1.  If the image is lossy-compressed like JPEG, we may end up double-compressing it in step 3.  And we're run a JPEG decoder (step 1) and possibly encoder (step 3) when we don't need to.
Here I replace the above with
1. Load the image path to bytes
2. Infer the MIME type from the path using python stdlib's `mimetypes`. (If it can't infer a MIME …
=> Speed up base64 encoding step for CV data logging

pyproject.toml
Upgrades HF datasets dependency ~~to 2.6.2~~ (update: unpinned) to prevent the error
```python
TypeError: can only concatenate str (not "int") to str
```
that we've been seeing when trying to load some datasets.  See https://github.com/huggingface/datasets/issues/5406
Verified that `load_dataset('mnist')` works on 2.6.2, but not on 2.6.1.
=> Upgrade datasets

dataquality/utils/hf_tokenizer.py, tests/integrations/spacy/test_spacy_ner.py
In `dataquality.utils.hf_tokenizer.LabelTokenizer`, there were a few accidental `if/if/else`s that should have been `if/elif/else`.
If the labels are BILOU, this causes the alignment process to convert them into BIO (unintended) while aligning them with HF tokens (intended).
This results in the model being trained to produce BIO spans, which the rest of dq will try to interpret as BILOU spans.  No valid BIO span is a valid BILOU span, so we'll record no predicted spans from the model ever.
=> Fix NER HF token alignment for BILOU data

dataquality/loggers/data_logger/text_ner.py
If you try to log a NER dataset with > 100k rows, and don't specify a custom logging batch size, you will currently get an error like
```
ValueError: First columns has length 50000, while column text_token_indices has length 150000
```
This happens because
- The default batch size is 100,000, so we are logging in multiple batches (2 of them)
- On the start of each batch, attributes like `self.texts` of `TextNERDataLogger` [get reset to the batch contents](https://github.com/rungalileo/dataquality/blob/main/dataquality/loggers/data_logger/text_ner.py#L191-L197).
- But, `self.text_token_indices_flat` is _not_ reset here.  And [it is used](https://github.com/rungalileo/dataquality/blob/main/dataquality/loggers/data_logger/text_ner.py#L599) as one of the columns in the Vaex frame for each …
=> Fix batched NER data logging

dataquality/clients/api.py, dataquality/loggers/data_logger/structured_classification.py, dataquality/loggers/logger_config/structured_classification.py, docs/Structured-Data.ipynb, tests/clients/test_api.py, tests/loggers/test_structured_classification.py
We were running into issues where:
- if you overwrote a run name, it would delete the feature importances. This was because we wrote the feature importances before `finish()` so it would delete the run in the DB and cascade the metrics. We now save the feature importances in the data logger `upload` after resetting the run name, so we are fine.
- There was also an issue with not json serializing numpy floats, which is fixed with `tolist()`
These have been tested on this run
https://console.dev.rungalileo.io/insights?dataframeColumns=confidence%3B%26data_error_potential%3B%26gold%3B%26petal+length+cm%3B%26petal+width+cm%3B%26pred%3B%26sepal+length+cm%3B%26sepal+width+cm%3B%26text&projectId=ee785245-7d39-47f8-9f31-4cbf5023fb1a&runId=56175074-567e-47db-b578-3f59e0b72e90&taskType=4
With …
=> Fix save feature importances

tests/loggers/test_image_classification.py
CV tests are failing intermittently ([example](https://github.com/rungalileo/dataquality/actions/runs/4236105384/jobs/7360933956)).  We're replacing the API url with google.com, but not mocking out the upload step, so (I think?) we're trying to upload to google.com and sometimes that doesn't work.
Replaced that with mocking out the entire upload.
=> Fix flaky CV tests

dataquality/__init__.py, dataquality/clients/api.py, dataquality/core/log.py, dataquality/loggers/data_logger/image_classification.py, dataquality/schemas/route.py, dataquality/utils/upload.py
Story details: https://app.shortcut.com/galileo/story/4429
=> chore: [sc-4429] rebuild multi-worker uploader for cv image uploading

dataquality/schemas/split.py
Added "val" and "valid" as acceptable split names for the validation split
This was needed for IC, since the split name determines the name of the val folder, which sometimes is "val" or "valid" instead of "validation"
=> add split names val and valid

.github/workflows/docs.yaml, .github/workflows/publish.yaml, .github/workflows/test.yaml
Resolves GitHub Actions warnings for deprecated runtimes that will soon be blocked.
=> chore(repo): Use latest versions of base GitHub Actions [sc-4740]

dataquality/__init__.py, dataquality/loggers/data_logger/base_data_logger.py, pyproject.toml
old release environment (`pypi.ngc...`) seems to have been taken down. 
I tested these versions in colab and they work for us. Updating dq version so we can release a working version out to customers
=> Cuda extra updates

dataquality/loggers/model_logger/semantic_segmentation.py, dataquality/schemas/semantic_segmentation.py, dataquality/utils/semantic_segmentation/polygons.py
Removes unneeded nesting in Polygons. Now that Rodrigo is drawing polygons on his own without OpenCV, let's remove the nesting and have the polygon json saved in a more intuitive format.
We also want polygon ids to be 0 indexed per image, not per (gt image vs. pred image)
=> Fix polygon id for image and remove nested pixels

dataquality/__init__.py, dataquality/integrations/setfit.py, dataquality/utils/cleanup.py, docs/autodocs/api/dataquality.rst, pyproject.toml, tests/integrations/setfit/test_setfit.py
Due to recent demand, I have converted the notebook to support setfit in the following way:
```python
from dataquality.integrations.setfit import watch
dq.init(task_type=TaskType.text_classification)
labels = ["nocat", "cat"]
dq.set_labels_for_run(labels)
split = "training"
batch_size = 3
ds_len = len(dataset)
dq_evaluate = watch(model)
dataset = dataset.map(lambda x, idx: {"id": idx}, with_indices=True)
for i in range(0, ds_len, batch_size):
print("batch", i)
batch = dataset[i : i + batch_size]
dq_evaluate(batch, split=split)
dq.finish()
```
[Issue in setfit repo](https://github.com/huggingface/setfit/issues/356)
=> added setfit support

dataquality/__init__.py, dataquality/utils/name.py, pyproject.toml, tests/utils/test_name.py
customers pointed out that sometimes the random names were being repeated. This happened because they were setting seeds in their code, which would cause the random generator to reset and return the same name.
UUIDs are not affected by the seed in the same way (tbh not sure how thats possible), but this prevents the issue from occuring. We tac on 5 characters from a uuid to make sure the name is random in the case of a seed being set
=> truly random names using uuid

pyproject.toml
Newest timm uses `typing.Final` which was introduced to python 3.8, python 3.7 linting is failing
https://github.com/rungalileo/dataquality/actions/runs/4960750400/jobs/8876653975
=> Pin timm for linting issue python 37

dataquality/integrations/setfit.py, dataquality/integrations/transformers_trainer.py, dataquality/utils/patcher.py, dataquality/utils/torch.py, dataquality/utils/transformers.py, tests/integrations/hf/test_text_classification_hf.py, tests/start/test_start_auto.py
- Use Patch class
- Unwatch on dq.finish / config reset
- Be able to load trainer from checkpoint and run inference
=> Refactoring trainer to support to run prediction and unwatch on dq.finish

dataquality/__init__.py, dataquality/clients/api.py, dataquality/core/init.py, dataquality/utils/name.py, tests/core/test_init.py, tests/utils/test_name.py
the core of this pr is the new `create_run_name` function + tests for it. 
User feedback suggested a nicer naming system. Instead of random names that are hard to parse, create run names that are today's date followed by the run_number that was created today.
tested with pytest, as well as:
With a new project
And an existing project
=> nicer naming system for runs

dataquality/clients/api.py, dataquality/internal.py
the old one was pretty outdated, and was missing the ability to get `ner_labels`, which made it break NER runs.
This one fixes that, and has a new home (because we needed to access `dq.metrics`
working ner run
good failure case (which tells you what to run) for the old function
=> new reprocess run

dataquality/schemas/semantic_segmentation.py, dataquality/utils/semantic_segmentation/polygons.py
=> Polygon uuid as strs 

dataquality/clients/api.py, dataquality/internal.py, dataquality/metrics.py, dataquality/schemas/route.py
1. Remove alerts before reprocessing
2. Handle inference and non-inference case
=> inference + alert clearing for reprocess_run

dataquality/loggers/model_logger/semantic_segmentation.py, dataquality/utils/semantic_segmentation/errors.py
https://app.shortcut.com/galileo/story/5475/dq-add-dep-at-a-polygon-level
=> Feature: Pred polygon dep (#1)

dataquality/schemas/task_type.py, tests/conftest.py
Just adding the new task type to keep `dataquality` aligned.
=> chore: Add prompt eval to task type

dataquality/loggers/model_logger/semantic_segmentation.py, dataquality/utils/semantic_segmentation/metrics.py
Compute iou locally instead of hitting hf hub - reduces dependency on hf hub and speeds up by about 4 seconds for 20 examples (55 down to 51) think this can be optimized further
=> Compute iou locally

dataquality/clients/api.py, dataquality/internal.py
=> Chore: Rename run internal fn

dataquality/__init__.py, dataquality/integrations/setfit.py, dataquality/loggers/base_logger.py, dataquality/utils/setfit.py, tests/integrations/setfit/test_setfit.py
Identified issues:
Issues when running the dq_evaluate due to the automatic removal of the patches
Further investigation:
Essentiallty the cleanup manager removed the patch. The other issue was that it was checking for the config before it was initialized.
=> Fix SetFit notebook issues v1

dataquality/integrations/torch_semantic_segmentation.py, dataquality/loggers/data_logger/image_classification.py, dataquality/utils/semantic_segmentation/metrics.py, dataquality/utils/upload.py
Fix for semseg in enterprise buckets
Notebook demonstrating the issue https://colab.research.google.com/drive/1Xc8Xzlc24nDwax1-7XXDD1RluEQqUIw6#scrollTo=CAqZVAbiXryu
In semseg we need to use the default buckets as specified by the backend (which are different if your cloud vendor is not minio), not the default minio bucket names
https://app.shortcut.com/galileo/story/5880/api-ml-test-runs-with-s3-gcs-private-buckets?ct_workflow=all&cf_workflow=500000005
=> Use the config buckets for semseg, fixes enterprise flow

dataquality/loggers/model_logger/base_model_logger.py
we've done this in a few places before uploading to Galileo, but we still write the batches to disk. This can really add up (f64 embeddings are huge).
Safely always downcast before writing to disk
=> downcast before saving batch

dataquality/__init__.py, dataquality/core/finish.py, dataquality/core/init.py, dataquality/utils/version.py, tests/core/test_finish.py, tests/core/test_init.py, tests/integrations/fastai/test_cv_fai.py, tests/integrations/fastai/test_text_fai.py, tests/integrations/hf/test_text_classification_hf.py, tests/integrations/keras/test_end2end_keras.py, tests/integrations/semantic/test_torch_semantic.py, tests/integrations/setfit/test_setfit.py, tests/integrations/torch/test_pt_text_classification.py, tests/integrations/torch/test_random_sampler.py, tests/integrations/ultralytics/test_cv_yolo.py, tests/loggers/test_image_classification.py, tests/loggers/test_tabular_classification.py, tests/start/test_start_auto.py, tests/start/test_start_hf.py, tests/start/test_start_keras.py, tests/start/test_start_pt.py, tests/test_dataquality.py, tests/test_utils/mock_request.py, tests/utils/test_dq_logger.py, tests/utils/test_version.py
=> fix: Move version validation to `init`, log warning instead of raising exception

dataquality/__init__.py, pyproject.toml
DQ doesn't work with pydantic 2
pydantic docs https://docs.pydantic.dev/dev-v2/migration/
```
>>> import dataquality
/Users/elliottchartock/Code/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
warnings.warn(message, UserWarning)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/elliottchartock/Code/.venv/lib/python3.9/site-packages/dataquality/__init__.py", line 39, in <module>
import dataquality.core._config
File "/Users/elliottchartock/Code/.venv/lib/python3.9/site-packages/dataquality/core/__init__.py", line 6, in <module>
from dataquality.analytics import Analytics
File "/Users/elliottchartock/Code/.venv/lib/python3.9/site-packages/ …
```
=> Pin pydantic below 2

.gitignore, dataquality/loggers/data_logger/seq2seq.py, dataquality/loggers/model_logger/seq2seq.py, dataquality/schemas/seq2seq.py, dataquality/utils/arrow.py
Small cleanup leading up to S2S sprint during onsite week
=> Chore: Documentation and input / output cols

dataquality/__init__.py, dataquality/analytics.py, dataquality/integrations/ultralytics.py
During the import of `dataquality`, start warning users that we're going to be dropping Python 3.7 support soon.
=> chore: Add py37 warning

tests/integrations/ultralytics/conftest.py
Turns out the test that was failing in #720 was just being flaky, because of an upstream change in settings management for `ultralytics` (https://github.com/ultralytics/ultralytics/pull/3790).
This improves how we handle it.
Tests:
=> fix: Use tmpdir for Ultralytics' YOLO config

.github/workflows/test.yaml
Codecov v1 is [deprecated](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1).
=> chore: Bump CodeCov action to v3

dataquality/loggers/data_logger/base_data_logger.py
Fixes an issue for those with cuml library installed where we tried to apply umap to embeddings even though semseg does not have any embeddings.
=> Fixes ci tests in example notebooks

dataquality/__init__.py, dataquality/clients/api.py, dataquality/core/log.py, dataquality/schemas/route.py
DQ side of https://github.com/rungalileo/api/pull/1185 to expose endpoint to customer 
https://app.shortcut.com/galileo/story/6863/api-endpoint-to-get-console-link-for-a-specific-project-run
=> Add endpoint for fetching url link

dataquality/integrations/torch.py
Warning for not finding the classification layer should not be thrown in the case of semseg so we ignore as we do not need to know layers, all we need to know are outputs and inputs
=> Only throw warning if not associated with semseg

dataquality/__init__.py, pyproject.toml
Use the latest version of [ipywidgets](https://pypi.org/project/ipywidgets/)
https://app.shortcut.com/galileo/story/6871/dq-pyproject-progress-bar-dependency#activity-6872
=> Pin ipywidgets to avoid iprogress bar import issue

.github/workflows/test.yaml, dataquality/__init__.py, pyproject.toml, tests/test_dataquality.py
https://app.shortcut.com/galileo/story/6981/dq-remove-support-for-python-3-7
Additional context: https://galileoteamworkspace.slack.com/archives/C02NSBN4ZK3/p1690213086742379
From https://www.python.org/downloads/release/python-3717/
```
Note: The release you are looking at is Python 3.7.17, the final security bugfix release for the legacy 3.7 series which has now reached end-of-life and is no longer supported. See the downloads page for currently supported versions of Python.
```
=> Remove python 37

dataquality/schemas/seq2seq.py, dataquality/utils/seq2seq/generation.py, tests/loggers/test_seq2seq.py, tests/utils/test_seq2seq_utils.py
This PR address this [ticket](https://app.shortcut.com/galileo/story/7910)
***Bug Description***
Currently generation works with small dataset sizes, but fails when we try over > 500 samples. We get some very strange error related to the `StructArray` that we have to use. When I talked to Ben about this, he mentioned that while possible this vaex `StructArray` design was fairly temperamental and error prone - which it seems a might be. 
***Proposed Solution***
The primary reason to use a vaex register function is to avoid bringing large amounts of data into memory through lazy evaluation. However, as addressed by a previous issue, we end up effectively forcing the computation of the `generated_data` to avoid lazy recomputation. …
=> fix: generation without vaex

dataquality/utils/seq2seq/generation.py, dataquality/utils/seq2seq/offsets.py
***Description***
This is a very small PR addressing a bug/annoyance when generating in `dq.finish()`. Essentially, during generation we rely no the function `align_tokens_to_character_spans` to create token alignment data. We do this at a per-sample level, since that is how we do generation. However, the `align_tokens_to_character_spans` function was initially developed as a batch processing methods. And with this, we use tqdm.
This becomes annoying when processing at the sample level because we constantly display `tqdm` for just a single iteration loop. See the demonstration bellow.
Constantly re-running `tqdm` with a single sample leads to this annoying flickering on the DQ side.
https://github.com/rungalileo/dataquality/assets/29869344/88536639-b9e1-4071-a781-74f147 …
=> Silencing tqdm during generation

dataquality/loggers/model_logger/seq2seq.py, dataquality/schemas/seq2seq.py, tests/loggers/test_seq2seq.py
Now that https://github.com/rungalileo/runners/pull/548 has been merged, we can deprecate from DQ
Ticket:
https://app.shortcut.com/galileo/story/7983/dq-deprecate-perplexity-from-dq?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
=> fix: remove perplexity from client

dataquality/integrations/seq2seq/s2s_trainer.py, dataquality/utils/torch.py
This PR helps prevent potential `CUDA` memory errors in `dq.auto()`. After training, `dq.finish()` uses some additional `GPU` memory for computing embeddings and for generation. If after training, there is very little available GPU RAM, we can run into big trouble!
Thankfully though, after training is complete, a lot of memory / data on the GPU is no longer needed for `dq.finish()`. For example, a big memory "hog" is the `optimizer`, which for many optimizers, effectively stores multiple copies of the entire model weights. 
To reclaim / free unused GPU memory, and pretty much safely ensure that `dq.finish()` will not error out we use the following pattern:
```
del  optimizer
...
torch.cuda.empty_cache()
import gc
gc.collect()
``` …
=> Free GPU Memory Before `dq.finish()` in `auto()`

dataquality/dq_auto/base_data_manager.py, dataquality/dq_auto/schema.py, dataquality/integrations/seq2seq/auto.py, dataquality/integrations/seq2seq/s2s_trainer.py, dataquality/integrations/seq2seq/schema.py, dataquality/utils/auto.py, docs/notebooks/Seq2Seq-Auto.ipynb
https://app.shortcut.com/galileo/story/8104/dq-auto-improvements-jsonl-file-support
While creating this PR, I realized there are a ton of places we can improve the other `auto` flows by using these schema configs. While we aren't making that refactor now, we are setting up the stage by creating base config schema here. 
In this PR we:
- Create base schema configs in `dataquality/dq_auto/schema.py`
- Create the Seq2Seq schema in `dataquality/integrations/seq2seq/schema.py`
- Extend `S2SDatasetManager` to load datasets from the config object (note this can go in the Base Manager in the future)
- Update the example notebook to use schema with an example for hf_data and an example with a local dataset
=> fix: s2s auto local file support

dataquality/__init__.py, dataquality/dq_auto/text_classification.py, dataquality/integrations/seq2seq/auto.py, dataquality/integrations/setfit.py, dataquality/loggers/data_logger/seq2seq.py, dataquality/utils/auto.py, dataquality/utils/setfit.py, pyproject.toml
https://app.shortcut.com/galileo/story/8226/dq-auto-support-for-logging-metadata
Tested locally and it works
https://console.dev.rungalileo.io/insights/4194b985-6c2c-459b-9199-5ed53135ce5a/dd896833-bf7f-4c2a-b51e-6aa8ede6ccaa?dataframeColumns=Unnamed%3A+0%3B%26category%3B%26data_error_potential%3B%26input%3B%26lang%3B%26perplexity%3B%26raw_data_hash%3B%26source%3B%26target&taskType=8
=> feat: s2s auto metadata

dataquality/__init__.py, dataquality/dq_auto/base_data_manager.py, dataquality/dq_auto/schema.py, dataquality/integrations/seq2seq/auto.py, dataquality/integrations/seq2seq/formatter.py, dataquality/utils/auto.py
We were running into some column renaming issues that I fix in this PR
I also made some edits to allow the user to pass in an upper limit to the dataset size that is configurable in DatasetConfig
A HF dataset has a default size limit that can be upped by the user
=> fix: auto alpaca

dataquality/__init__.py, dataquality/integrations/seq2seq/formatters/chat.py
`.find()` returns -1 if str is not found, so the min was returning -1 for first turn of all chats
this gracefully handles first turn, so that if find returns -1 we just take the last 512 tokens
=> fix: chat auto, gracefully handle when str not found

dataquality/__init__.py, dataquality/dq_auto/schema.py
```python
>>> bool(dataset)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-c57750f91409>](https://localhost:8080/#) in <cell line: 1>()
----> 1 bool(dataset)
[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __nonzero__(self)
1525     @final
1526     def __nonzero__(self) -> NoReturn:
-> 1527         raise ValueError(
1528             f"The truth value of a {type(self).__name__} is ambiguous. "
1529             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
=> fix: pandas df truthiness

dataquality/__init__.py, dataquality/integrations/seq2seq/s2s_trainer.py, dataquality/loggers/data_logger/seq2seq.py, dataquality/utils/seq2seq/offsets.py, tests/utils/test_seq2seq_offset.py
user cleaner vaex pattern of adding to df and return full DF
we also materialize `input_cutoff` to speedup larger runs
=> fix(chore): cleanup s2s offsets

dataquality/integrations/seq2seq/auto.py, dataquality/integrations/seq2seq/s2s_trainer.py
Continuing https://app.shortcut.com/galileo/story/8588/dq-seq2seq-auto-with-0-epochs-just-pass-over-data-no-backwards
Succesfully tested with run https://console.dev.rungalileo.io/insights/e24eb571-8eaf-45a1-beb0-86c6488f4f1a/44cc2011-1bfb-48f6-8746-4a1eae8b61d4?dataframeColumns=data_error_potential%3B%26input%3B%26instruction%3B%26perplexity%3B%26target&taskType=8
=> Seq2Seq: Only (force-)add val data if we fine-tune

dataquality/core/log.py, dataquality/loggers/model_logger/base_model_logger.py, dataquality/loggers/model_logger/image_classification.py, dataquality/loggers/model_logger/semantic_segmentation.py, dataquality/loggers/model_logger/seq2seq/seq2seq_base.py, dataquality/loggers/model_logger/text_classification.py, dataquality/loggers/model_logger/text_multi_label.py, dataquality/loggers/model_logger/text_ner.py
In doing a refactor I noticed that labels are never used in model loggers, so let's remove them!
=> fix: remove unused labels

dataquality/integrations/ultralytics.py, pyproject.toml
Ultralytics v8.0.209 removed the `model` from the `validator`'s attributes
=> Fix ultraytics validator

dataquality/integrations/seq2seq/core.py, dataquality/integrations/seq2seq/s2s_trainer.py, dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/loggers/logger_config/seq2seq/seq2seq_base.py, dataquality/loggers/model_logger/seq2seq/formatters.py, dataquality/loggers/model_logger/seq2seq/seq2seq_base.py, dataquality/schemas/seq2seq.py, docs/notebooks/Seq2Seq_Decoder_Only_Dq_Fake_Data.ipynb, docs/notebooks/Seq2Seq_Dq_Fake_Data.ipynb, docs/notebooks/Tabular-Data.ipynb, tests/integrations/seq2seq/test_core.py, tests/integrations/seq2seq/test_hf.py, tests/loggers/test_seq2seq.py, tests/utils/test_seq2seq_offset.py, tests/utils/test_seq2seq_utils.py
https://app.shortcut.com/galileo/story/9036/dq-make-the-model-a-manual-param-for-watch-fn?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
In this PR we:
- Rename `Seq2SeqModelTypes` -> `Seq2SeqModelType`
- Make `model` optional in watch
- Make `model_type` required in watch
- Move watch fn to `core`
=> chore: model optional model type required

dataquality/__init__.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, tests/loggers/test_seq2seq.py
Ensure formatter is set. Updated pytests.
Tested e2e as well and verified it worked https://console.enterprise.rungalileo.io/insights/4c6a2573-bcf9-4b4e-8f39-a270a387b5c6/fa74f493-b2ae-44da-9ea2-f50620e1c24b?dataframeColumns=User_skip_use_as_completion%3B%26User_toxicity%3B%26chat_id%3B%26data_error_potential%3B%26input%3B%26perplexity%3B%26raw_data_hash%3B%26target%3B%26turn_id&groupedBy=chat_id&tab=em&insightsTab=clusters&taskType=8 
(credentials in 1pass)
=> fix: set formatter in seq2seq data logger

dataquality/__init__.py, dataquality/integrations/seq2seq/core.py
***Description***
Final testing showed that no model logging still required the test split generation even when `generation_splits` was empty
```
[/usr/local/lib/python3.10/dist-packages/dataquality/utils/seq2seq/generation.py](https://localhost:8080/#) in add_generated_output_to_df(df, model, tokenizer, max_input_tokens, generation_config)
213         Updated Dataframe with the generated columns added (see above)
214     """
--> 215     model.eval()
216     generated_data = BatchGenerationData()
217
AttributeError: 'NoneType' object has no attribute 'eval'
```
=> fix: remove test from generation splits

dataquality/loggers/base_logger.py, dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/schemas/seq2seq.py, tests/loggers/test_seq2seq.py
Goal is to compute high dep tokens https://app.shortcut.com/galileo/story/9232/dq-save-nessec-column-for-high-dep-tokens?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
The DQ work requires saving the target tokens. We later groupby them (and the ID is not enough as we need the tokens for the UI).
Decoding the target token ids is fast enough in my opinion. Here it's taking ~10 sec for 10K rows and ~1M tokens
=> feat: s2s add high dep tokens

dataquality/__init__.py, dataquality/loggers/base_logger.py, tests/test_dataquality.py
https://app.shortcut.com/galileo/story/9579/dq-adding-x-y-data-x-or-data-y-as-metadata-succeeds-but-should-not
Customer ran into issues when logging x as metadata
=> fix: disallow emb cols as metadata

dataquality/__init__.py, pyproject.toml
Fix IC integrations tests that are failing here https://github.com/rungalileo/deploy/actions/runs/7113620750/job/19365964373
Context: 
https://stackoverflow.com/questions/77433096/notimplementederror-loading-a-dataset-cached-in-a-localfilesystem-is-not-suppor
=> fix: bump datasets to 2.14.6

dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/loggers/model_logger/base_model_logger.py, dataquality/schemas/seq2seq.py, dataquality/utils/seq2seq/decoder_only.py, dataquality/utils/seq2seq/generation.py, docs/notebooks/Seq2Seq_Decoder_Only_Dq_Fake_Data.ipynb, tests/loggers/conftest.py, tests/loggers/test_seq2seq.py, tests/utils/test_seq2seq_utils.py
In this PR we focus on adding generation support for Decoder Only models. In doing so, we also re-structure parts of the generation workflow. Below is an executive summary of the changes added!
The primary differences between generation for EncoderDecoder and DecoderOnly models are:
1. The df column / sample data used for generation
2. The generation processing for each sample (i.e. the logic previously in the `utils.seq2seq.generation.generate_sample_output` function).
Thankfully, similar to the processing of model logprob outputs, after sample level generation / processing, logic can be shared around token alignment and the overall saving of information to the dataframe - since in the end we expect the same information for generated data.
**The main structural change is to address (2) …
=> Decoder Only Generation Support

dataquality/__init__.py, dataquality/core/log.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/loggers/logger_config/base_logger_config.py
https://app.shortcut.com/galileo/story/10245/dq-don-t-log-custom-embs-if-not-passed-in
We create random embs for other task types if they are not passed in. But for S2S we should just ignore (since no custom embs is permitted) 
Will fix these emb squares
=> fix: ignore embs if not passed

dataquality/__init__.py, dataquality/clients/api.py, dataquality/core/auth.py, dataquality/utils/auth.py, pyproject.toml, tests/clients/test_api.py, tests/conftest.py
https://app.shortcut.com/galileo/story/10174/dq-api-client-token-refresh
We should have an automatic token refresh similar to LLM Monitor and Prompt: https://github.com/rungalileo/llm-monitor/blob/1a42e5275dc5d4bb6b11219284269f44b02cab3b/llm_monitor/utils/api_client.py#L72-L89
https://fmpm.dev/mocking-auth0-tokens
My local token was expired but it used the local env to refresh succesfully.
```
>>> import os
>>> import jwt
>>> from time import time
>>> from dataquality.core._config import config
>>> os.environ["GALILEO_USERNAME"] = "<redacted>"
>>> os.environ["GALILEO_PASSWORD"] = "<redacted>"
>>> token = config.token
>>> exp = jwt.decode(token, options={"verify_signature": False})
>>> exp
{'sub': '<redacted>', 'id': '<redacted>', 'exp': 1700681062}
>>> time() > exp["exp"]
True
>>> …
```
=> feat: token refresh

dataquality/__init__.py, dataquality/loggers/data_logger/seq2seq/formatters.py, dataquality/loggers/data_logger/seq2seq/seq2seq_base.py, dataquality/utils/seq2seq/offsets.py
***Issue Description***
Right now, for Decoder-Only models, there is a small mis-alignment bug between what is processed by the DQ client and what we see in the UI. Essentially, there is a small disconnect (for many situations) between what the model "sees" (as input and returns alignment / token data on) and <Target> string that we display in the UI.
**Current Flow**
- User logs <Target> string column - this is what will be displayed in the UI and what we expect to compute aligned token info for. However, we cannot directly compute alignment / token info since decoder only models process the full <Input> + <Target> through what we call the `formatted_prompt`
- User logs `formatted_prompt`
- Locate response template
- Slice off all characters / tokens following the response template
- …
=> Fix misalignment between token offsets returned from the API and samples in the UI 

dataquality/__init__.py, dataquality/integrations/seq2seq/core.py, dataquality/loggers/logger_config/seq2seq/seq2seq_base.py, dataquality/utils/seq2seq/generation.py, pyproject.toml
Addresses two main issues:
1. Allowing for generation with `PEFTModels` from hf. This will be nearly the majority use case when people are fine-tuning very large models like Llama-2, since the general paradigm is to apply Parameter Efficient FT methods such as LORA and QLORA. Annoyingly a `PEFTModel`, while related to the hf library, comes from its own package `peft` and is not a subclass of a `PreTrainedModel`.
2. When generating, setting `model.config.use_cache=True` is very important for speed purposes. Otherwise generation is prohibitively slow!
=> feat: generation peft

dataquality/__init__.py, dataquality/core/auth.py, dataquality/internal.py, dataquality/schemas/task_type.py, tests/integrations/setfit/test_setfit.py, tests/start/test_start_auto.py
https://app.shortcut.com/galileo/story/11305/dq-logged-in-as-none?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
https://app.shortcut.com/galileo/story/11306/dq-reprocess-broken-for-finetune?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
Tested login wiht a few flows and was able to reproduce and fix:
```
>>> dq.login()
📡 https://console.dev.rungalileo.io
🔭 Logging you into Galileo
🚀 You're logged in to Galileo as galileo@rungalileo.io!
Use logout() if you want to change users
```
Tested reprocess locally and it worked like a charm 
```
>>> reprocess_run("Seq2Seq_DecoderOnly_Log_Logprobs", "2023-11-13_9")
All alerts removed for run Seq2Seq_DecoderOnly_Log_Logprobs/2023-11-13_9
Job default successfully resubmitted. New results will be available soon at …
```
=> fix: logged in as none and reprocess finetune fixes

dataquality/loggers/data_logger/seq2seq/seq2seq_base.py
Changed to make the errors more explicit as I ran into some trouble while using the data logger.
=> fix(seq2seq): Include action info in data logger errors

dataquality/__init__.py, dataquality/integrations/setfit.py, dataquality/integrations/torch.py, dataquality/integrations/ultralytics.py, dataquality/internal.py, dataquality/loggers/base_logger.py, dataquality/loggers/data_logger/base_data_logger.py, tests/integrations/setfit/test_setfit.py, tests/loggers/test_seq2seq.py, tests/test_telemetrics.py
Re-introducing the old reprocess run logic since it was useful for transferred runs that don't have a preexisting job
=> fix: re-add og internal reprocess fn

.github/workflows/publish-docs.yaml
**Description:** `workflow_dispatch` is a terrible idea when in a public repo.
I had added it so that I could debug in case the run after #832 failed. It didn't so we can remove it.
=> ci(docs): Disable running with `workflow_dispatch` since this is a public repo

.github/workflows/publish-docs.yaml
[CI for docs failed](https://github.com/rungalileo/dataquality/actions/runs/8116632585/job/22187091557) after #833 because of missing this.
=> ci(docs): Install `poetry` in setup step

.github/workflows/pre-commit.yaml, .github/workflows/stale.yaml
**Description:** In my attempt to remove the dependence on internal workflows in #838, I mixed up and made changes to the workflow from #837. This should bring them back into alignment as we expect them to be.
Oops!
=> ci: Fix pre-commit and stale workflows to remove mixup

.github/workflows/publish-docs.yaml
The action [for docs failed](https://github.com/rungalileo/dataquality/actions/runs/8163197346/job/22315882912) after v2.0.1 so fixing that.
=> ci: Install root package in docs workflow

.github/workflows/publish-docs.yaml
The install was still missing a couple things.
I just ran this E2E locally now so everything should work fine next release onwards.
=> ci: Install the `docs` extras when building docs

dataquality/__init__.py, dataquality/core/init.py, pyproject.toml, tests/core/test_init.py, tests/integrations/fastai/test_cv_fai.py, tests/integrations/fastai/test_text_fai.py, tests/integrations/keras/test_end2end_keras.py, tests/integrations/semantic/test_torch_semantic.py, tests/integrations/setfit/test_setfit.py, tests/integrations/torch/test_pt_text_classification.py, tests/integrations/torch/test_random_sampler.py, tests/integrations/ultralytics/test_cv_yolo.py, tests/start/test_start_auto.py, tests/start/test_start_hf.py, tests/start/test_start_keras.py, tests/start/test_start_pt.py
**Shortcut:**
https://app.shortcut.com/galileo/story/14149/qa-bug-tc-mltc-notebooks-problem-with-creating-new-project
**Description:**
Remove the major version mismatch as noticed in ☝️ 
This concept has not been kept up with as api has been built towards more clients than just DQ 
**Tests:**
=> chore: remove version check warning

poetry.lock, pyproject.toml
**Description:**
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB 3.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of cuml-cu12 to determine which version is compatible with other requirements. This could take a while.
The conflict is caused by:
dataquality[cuda12] 2.1.1 depends on raft-dask-cu12<25.0.0 and >=24.2.0; extra == "cuda" or extra == "cuda12"
cuml-cu12 24.2.0 depends on raft-dask-cu12==24.2.*
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: Cannot install dataquality and dataquality[cuda12]==2.1.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit …
```
=> fix(cuda12): pin version

dataquality/core/finish.py, dataquality/integrations/transformers_trainer.py, dataquality/utils/upload_model.py, tests/core/test_finish.py
**Description:**
Currently we don't save the tokenizer when uploading a model
If a custom model is used besides distill-bert we cant reconstruct the tokenizer
=> feat(model_upload): Add tokenizer to upload_model_to_dq function

dataquality/core/auth.py
We have been calling JWT tokens API keys...
=> fix(login): Use the correct name in login message

dataquality/clients/api.py, dataquality/core/init.py, tests/core/test_init.py
The `is_public` field has been replaced by sharing projects with users
and groups.
=> feat(core): Remove `is_public` from project creation
